### ISSUE TITLE
[8] detail page에 fetch코드 추가

### ISSUE THREAD

**Issue by revlanc** [codesquad-project-team/frontend#23]
## branch name 
feat/8-detail-page-add-fetch

## 구현내용
- 포스트 상세 페이지에 하드코딩되어있던 data부분을 fetch로 수정하기
- 리액트 라우터로 props 넘겨받아서 fetch 요청보내기
  - main page로부터 postId값을 넘겨받아야함
- RelatedPost에 key props 필요

**Comment by leehwarang** [comment]
- RelatedPost 컴포넌트에서 업데이트된 API 적용 및 fetch  코드 리팩토링
- LocationCarousel 컴포넌트에서 fetch 요청 후 받은 image 의 갯수에 따라 Carousel 컴포넌트 만드는 함수 추가

**Comment by revlanc** [comment]
미셸~ 이슈는 수동으로 클로즈 안해도 돼요 ㅎ
PR에 이슈 언급해두면 PR머지될 때 자동으로 클로즈 됩니다 ㅎㅎ
