### ISSUE TITLE
[21] 프로필 편집 페이지에서 input 값 수정시 프로필 이미지 사라지는 버그 

### ISSUE THREAD

**Issue by leehwarang** [codesquad-project-team/frontend#49]
## branch name
- fix/21-profile-image-hide

## 구현할 내용

- 처음 프로필 페이지 들어왔을 때 프로필 이미지 정상적으로 보여짐 

<img width="1440" alt="스크린샷 2019-11-10 오후 1 04 39" src="https://user-images.githubusercontent.com/18614517/68538613-bf822800-03ba-11ea-87f4-31961fb303f5.png">

- input값 수정했을 때 프로필 이미지 사라짐 

<img width="1440" alt="스크린샷 2019-11-10 오후 1 04 48" src="https://user-images.githubusercontent.com/18614517/68538614-cb6dea00-03ba-11ea-9e73-3e5b7f4099fc.png">

**Comment by dev-allenk** [comment]
resolved by #72 

resolve 뒤에 이슈번호 두개 연달아서 쓰면 뒤에껀 자동으로 이슈 클로즈 안되더라구요. 불편..ㅎㅎ
요 이슈는 해결되었으니 닫을게요~
