### ISSUE TITLE
[32] 동일한 이미지를 여러 개 업로드 했을 시에, 대표 이미지 및 삭제할 이미지 선택 버그 발생 

### ISSUE THREAD

**Issue by leehwarang** [codesquad-project-team/frontend#67]
## branch name
- fix/32-image-select-error

## 구현내용
- 대표 이미지와 삭제할 이미지를 선택했을 때, 어떤 이미지가 선택 되었는지 파악하기 위해 현재는 `src` 를 기준으로 하기 때문에 발생하는 버그. 해결 필요 

## 참고사항
-

**Comment by leehwarang** [comment]
@revlanc  지난 번에 남겨줬던 [이 코멘트](https://github.com/codesquad-project-team/frontend/pull/62/files#r349981495) 와 연관된 것 같기도 한데, 이 때 **DOM 구조 변경에 취약**하다는 말이 어떤 의미였는지 좀 더 설명해 줄 수 있을까요?

**Comment by revlanc** [comment]
> @revlanc 지난 번에 남겨줬던 아래 이미지의 코멘트와 연관된 것 같기도 한데, 이 때 **DOM 구조 변경에 취약**하다는 말이 어떤 의미였는지 좀 더 설명해 줄 수 있을까요?

이 현상은 생각하지 못했는데 미셸이 파악한 원인과 연관된 것 같긴 하네요.
```javascript
    const deletedImage = e.target.previousSibling.src;
    const targetIndex = images.previewUrls.findIndex(
      url => url === deletedImage
    );
```
제 코멘트는 이런의미였어요.
> 현재 엘리먼트(e.target)로부터 목표한 엘리먼트를 찾을 때 '이전 엘리먼트'로 찾는다면 만약 현재 엘리먼트와 목표 엘리먼트 사이에 다른 엘리먼트가 추가되면 '이전 엘리먼트'가 목표한 엘리먼트가 아닐 수 있다. 따라서 이런 변경사항이 발생한다면 여기 코드도 수정이 필요하다.

설명 더 필요하면 리플 주세요!
