### ISSUE TITLE
[33] 프로필 페이지에 필요한 기능 구현(팔로우, 포스트 목록)

### ISSUE THREAD

**Issue by dev-allenk** [codesquad-project-team/frontend#69]
## branch name
- feat/33-add-follow-feature

## 구현내용
- [x] 유저 프로필 페이지로 들어왔을 때 해당 유저의 활동 정보(게시글 수, 팔로잉, 팔로워 수) 표시하는 기능
  - 현재 하드코딩된 부분 api 활용하도록 수정
- [x] 유저 프로필 페이지 진입 시 해당 유저의 포스트 목록 가져오도록 api 에 writerId 쿼리 추가
- [x] 팔로우 기능 추가

## 참고사항
- 로그아웃 피쳐는 따로 분리할게요.(마일스톤에 맞추려면 작게 나눠야할것 같아요.)

**Comment by revlanc** [comment]
- [ ] 로그인 되지 않은 상태에서 팔로우 누를 경우 로그인 모달 띄우기
