### ISSUE TITLE
[42] 포스트 수정, 삭제 기능 구현

### ISSUE THREAD

**Issue by dev-allenk** [codesquad-project-team/frontend#87]
## branch name
- feat/42-post-edit-and-delete

## 구현내용
- [x] DetailPage 에 헤더영역 만들기
- [x] 헤더영역 오른쪽에 '수정', '삭제' 버튼 구현하기
- [x] 수정버튼 클릭할 경우 `/post/edit` 으로 이동하고 포스트 수정 가능
- [x] 삭제버튼 클릭할 경우 삭제여부 확인 후 삭제

**Comment by leehwarang** [comment]
그렇다면 이 이슈는 제가 가지고 가겠습니다 ㅎㅎ

**Comment by dev-allenk** [comment]
@leehwarang  그거 해주세요. 로그인 안된 상태에서 로그인 필요한 페이지 접속하려고 하면 에러처리해주는거 ㅎㅎ
