### ISSUE TITLE
[44] LoginModal 관련 이슈 로직 수정 

### ISSUE THREAD

**Issue by leehwarang** [codesquad-project-team/frontend#91]
## branch name
- refactor/44-login-modal-issue

## 구현내용
- LoginModalContext 삭제 예정
- Header 컴포넌트가 가지고 있는 `clickedSignup, clickedSignin` 관련 상태와 함수를 LoginContext 에서 관리하도록 수정 예정

## 참고사항
- 미팅 때 구두로 이야기한 사항이라 관련해서 대화했던 내용만 [링크](https://github.com/codesquad-project-team/frontend/pull/73#pullrequestreview-336905347)로 남겨 놓을게용!

**Comment by dev-allenk** [comment]
branch name에 이슈넘버 빠져있어서 수정했어요~
뭔가.. 커스텀 훅을 활용할 수도 있을것 같은 기분이 드네요
